name: K6 Load Test

on:
  push:
    branches: [ master ]

jobs:
  k6-load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install k6
        run: |

          sudo apt update
          sudo apt install -y gpg


          sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D83BC0D


          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list


          sudo apt update
          sudo apt install -y k6

      - name: Run K6 load test
        run: k6 run load_tests_k6/login_load_test.js