name: K6 Load Test

on:
  push:
    branches: [ master ]  # Или другую ветку, если нужно

jobs:
  k6-load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install k6
        run: |
          # Устанавливаем зависимости
          sudo apt update
          sudo apt install -y gpg

          # Скачиваем ключ k6 напрямую и добавляем его
          curl -s https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg

          # Добавляем репозиторий k6
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list

          # Обновляем пакеты и устанавливаем k6
          sudo apt update
          sudo apt install -y k6

      - name: Run K6 load test
        run: k6 run load_tests_k6/login_load_test.js